Jhonatan Garcia Castellanos
RF 1.1	El sistema debe permitir al usuario ingresar nombre, apellido, correo electrónico y contraseña para registrarse.
RF 1.2	El sistema debe almacenar la información del usuario en la base de datos.
RF 1.3	El sistema debe validar que el correo electronico no se haya registrado antes
RF 1.4	El sistema debe exigir que la contraseña cumpla con una política de seguridad (mínimo 8 caracteres, una mayúscula y un número).
RF 1.5	El sistema debe permitir confirmar la contraseña ingresando el campo dos veces.
RF 1.6	El sistema debe enviar un correo de verificación al usuario tras completar el registro.
RF 1.7	El sistema debe mostrar mensajes de error específicos por cada campo que no cumpla las validaciones de registro de usuario.
RF 1.8	El sistema debe permitir al usuario aceptar los términos y condiciones como requisito para finalizar el registro.
RF 2.1	El sistema debe permitir el inicio de sesión.
RF 2.2	El sistema debe permitir el cierre de sesión de forma manual y automática para garantizar la seguridad de la cuenta del usuario
RF 2.3	El sistema debe tener acceso al formulario de recuperación De contraseña
RF 3.1	El sistema debe tener Control de Inventarios: Registro, seguimiento y conteo automatizado de productos.
RF 3.2	El sistema debe tener agregar, editar y eliminar productos.

Johan Sebastian Garcia Mora
RF 3.3	El sistema debe contar con Consultar stock en tiempo real con alertas.
RF 3.4	El sistema debe contar con Registrar productos con escáner.
RF 4.1	El sistema debe contar con Creación de PQR
RF 4.2	El sistema debe contar con Tipos de PQR
RF 4.3	El sistema debe contar con Ver y gestionar mensajes de usuarios.
RF 4.4	El sistema debe contar con Carga de archivos adjuntos
RF 4.5	El sistema debe contar con Generación de número de radicado de PQR
RF 4.6	El sistema debe contar con Confirmación de recepción y estado de PQR
RF 5.1	El sistema debe contar con Registro de ventas
RF 5.2	El sistema debe contar con calculo autmatico
RF 5.3	El sistema debe contar con Generación de comprobante
RF 5.4	El sistema debe contar con Métodos de pago
RF 5.5	El sistema debe contar con Consulta de ventas

Jhon Jairo Trilleras Jimenez
RF 5.6	 El sistema debe contar con cancelación de pedido y estado de venta
RF 6.1	Registro de Proveedores
RF 6.2	Categorización de Insumos
RF 6.3	Carga de Documentación Legal
RF 7.1	Selección de Pagos Pendientes
RF 7.2	Generación de Comprobante
RF 7.3	Notificación de Pago Realizado
RF 8.1	El sistema deberá verificar que el número de comprobante emitido por el proveedor no exista previamente en la base de datos para evitar registros duplicados.
RF 8.2	El sistema deberá asignar automáticamente la fecha, la hora exacta del servidor y el usuario logueado que está procesando la entrada de mercancía.
RF 8.3	El sistema deberá permitir la eliminación individual de cualquier fila de producto insertada por error en la tabla de la compra antes de su almacenamiento.
RF 9.1	El sistema debe permitir al usuario autenticado modificar sus datos personales de contacto directamente desde la configuración de su cuenta.
RF 9.2	El sistema debe permitir al usuario subir o reemplazar de manera opcional una imagen digital para personalizar su avatar dentro de la plataforma.
