Jhonatan Garcia Castellanos
RF 1.1	El sistema debe permitir el inicio de sesión para restringir el acceso según el rol.
RF 1.2	Gestión de Ventas: Debe permitir el registro de transacciones comerciales de manera digital
RF 1.3	Control de Inventarios: Registro, seguimiento y conteo automatizado de productos.
RF 2.1	Agregar, editar y eliminar productos.
RF 2.2	Registrar movimientos de stock (entradas/salidas).
RF 2.3	Consultar stock en tiempo real con alertas.
Rf 3.1	Subir fotos/videos en reportes.
Johan Sebastian Garcia Mora
Rf 3.2	Clasificar PQR automáticamente.
Rf 3.3	Ver y gestionar mensajes de usuarios.
RF 4.1	Registrar productos con escáner.
RF 4.2	Alertas de stock mínimo.
RF 4.3	El usuario tendrá una opción de cancelación de compra.
RF5.1	Registro de ventas
RF5.2	Cálculo automático
Jhon Jairo Trilleras Jimenez
RF5.3	Generación de factura o comprobante
RF5.4	Actualización de inventario
RF5.5	Cancelación de facturas
RF5.6	Métodos de pago
RF5.7	Consulta de ventas
RF5.8   Union de interfaz
RF5.9   Revisar que todo este bien 