Jhonatan Garcia Castellanos
RF 1.1	El sistema debe permitir al usuario ingresar nombre, apellido, correo electrónico y contraseña para registrarse.
RF 1.2	El sistema debe validar que el correo electrónico tenga un formato válido antes de completar el registro.
RF 1.3	El sistema debe validar que el correo electronico no se haya registrado antes
RF 1.4	El sistema debe exigir que la contraseña cumpla con una política de seguridad (mínimo 8 caracteres, una mayúscula y un número).
RF 1.5	El sistema debe permitir confirmar la contraseña ingresando el campo dos veces.
RF 1.6	El sistema debe enviar un correo de verificación al usuario tras completar el registro.
RF 1.7  El sistema debe mostrar mensajes de error específicos por cada campo que no cumpla las validaciones.
RF 1.8	El sistema debe permitir al usuario aceptar los términos y condiciones como requisito para finalizar el registro.
RF 2.1	El sistema debe permitir el inicio de sesión para restringir el acceso según el rol.
RF 2.2	El sisrema debe validar el formato de correo electronnico que se encuentra registrado en la base de datos
RF 2.3	el sistema debe tener Ingreso de Contraseña
RF 2.4	el sistemas debe tener Validación de credenciales
RF 2.5	el sistema debe tener Cierre  de sesión automático
RF 2.6	el sistema debe tener Cierre de sesión manual
RF 2.7	el sistema debe tener acceso al formulario de recuperación De contraseña
RF 3.1	el sistema debe tener Control de Inventarios: Registro, seguimiento y conteo automatizado de productos.
RF 3.2	el sistema debe tener agregar, editar y eliminar productos.
Johan Sebastian Garcia Mora
RF 3.3	el sistema debe tener registrar movimientos de stock (entradas/salidas).
RF 3.4	El sistema debe contar con Consultar stock en tiempo real con alertas.
RF 3.5	El sistema debe contar con registro de entradas de inventario
RF 3.6	El sistema debe contar con registro de salidas de inventario
RF 4.1	El sistema debe contar con Creación de PQR
RF 4.2	El sistema debe contar con Tipos de PQR
RF 4.3	El sistema debe contar con Ver y gestionar mensajes de usuarios.
RF 4.4	El sistema debe contar con Carga de archivos adjuntos
RF 4.5	El sistema debe contar con Generación de número de radicado
RF 4.6	El sistema debe contar con Confirmación de recepción
RF 5.1	El sistema debe contar con Registro de usuario
Rf 5.2	El sistema debe contar con Registro por parte del usuario
RF 5.3	El sistema debe contar con Validación de datos únicos
RF 5.4	El sistema debe contar con Asignación de roles
RF 5.5	El sistema debe contar con Registrar productos con escáner.
RF 5.6	El sistema debe contar con Alertas de stock mínimo.
Jhon Jairo Trilleras Jimenez
RF 5.7	El sistema debe contar con El usuario tendrá una opción de cancelación de compra.
RF 6.1	El sistema debe contar con Registro de ventas
RF 6.2	El sistema debe contar con Cálculo automático
RF 6.3	El sistema debe contar con Generación de factura o comprobante
RF 6.4	El sistema debe contar con Actualización de inventario
RF 6.5	El sistema debe contar con Cancelación de facturas
RF 6.6	El sistema debe contar con Métodos de pago
RF 6.7	El sistema debe contar con Consulta de ventas
RF 6.8	El sistema debe contar con Gestión de Ventas: Debe permitir el registro de transacciones comerciales de manera digital
RF 7.1	Registro de Proveedores
RF 7.2	Categorización de Insumos
RF 7.3	Evaluación de Desempeño
RF 7.4	Carga de Documentación Legal
RF 8.1	Selección de Facturas Pendientes
RF 8.2	Generación de Comprobante
RF 8.3	Notificación de Pago Realizado